### ISSUE TITLE
Exception not integer for image size

### ISSUE THREAD

**Issue by palitu** [trebonius0/Photato#26]
I cannot remember the exact error, but i get some errors where there is an uncaught except when the image size is not an integer.

not sure if you have seen this, when it happens again i will post the logs, but they are fairly vague, not telling me which file had the issue.  It also kills the process

**Comment by CrashLaker** [comment]
Not sure if it's the same error we're talking about but I'm facing the following error when Photato is trying to parse a .MOV or .MPG file (a file it shouldn't be reading). 

```

Exception in thread "main" java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at photato.core.metadata.exif.ExifMetadata.getImageHeight(ExifMetadata.java:102)
        at photato.core.metadata.Metadata.<init>(Metadata.java:26)
        at photato.core.metadata.MetadataAggregator.getMetadatas(MetadataAggregator.java:89)
        at photato.core.PhotatoFilesManager.runInitialFolderExploration(PhotatoFilesManager.java:173)
        at photato.core.PhotatoFilesManager.<init>(PhotatoFilesManager.java:67)
        at photato.Photato.main(Photato.java:78)
```
Thing is. I wanna keep the videos there but I don't want them to show at the gallery neither I want them to be read. Is there a way to select only the pictures by matching them with a regex pattern? '/.*(jpg|jpeg|png)$/gi'

**Comment by palitu** [comment]
This looks to be the exact error i have!

Well, at least it should be catching the error, logging it and moving on.
